### ISSUE TITLE
Issue with backslashes

### ISSUE THREAD

**Issue by ShayBox** [cassaundra/wildflower#10]
I found this trying to match paths with globs but it seems the source must have double-escaped backslashes to match.
```rust
Pattern::new("C:\\").matches("C:\\") // false
Pattern::new("C:\\\\").matches("C:\\") // true
```

EDIT: Temporary workaround `.replace('\\', "\\\\")` on source  
EDIT2: Changing this behavior now would be a breaking change and require bumping to version `0.4`

**Comment by cassaundra** [comment]
Thanks for the report!

`C:\\` in source becomes `C:\` after Rust's escaping, which wildflower just reads as a dangling escape character. It's undefined in wildflower's spec how a dangling escape should be treated, but for consistency's sake, I think it would be better to ignore them.

As a workaround, I would recommend just using raw strings here, like one would with the `regex` crate:

```rust
Pattern::new(r"C:\\").matches("C:\\") // true!
```

I'll update the docs to use raw strings in the examples so this is less confusing in the future though, so this is very helpful feedback.

**Comment by ShayBox** [comment]
How would I use raw strings when I have 2 string variables not initialized directly in code
